services:
  - type: web
    name: readerconnect-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    autoDeploy: true

  - type: web
    name: readerconnect-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s dist
    autoDeploy: true
