services:
  - type: web
    name: readerconnect-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    autoDeploy: true

  - type: static
    name: readerconnect-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    autoDeploy: true
